language: scala

before_install:
  - export PATH="$PATH:./vendor/bundle"

install:
  - rvm use 2.2.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt makeMicrosite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - vendor
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
